import Head from 'next/head'
import Image from 'next/image'
import React from 'react'

import home from '../styles/Home.module.css'

import Header from '../lib/header'
import Login from '../lib/login'
import Register from '../lib/register'
import Restaurant from '../lib/restaurant'

import fetchJson from '../lib/fetchJson'

import test from '../lib/test'

function appReducer(state,action){
  // console.log(' >> ', state, action )

  switch(action.type){
    case 'page':
      return {...state, ...action.data }
    case 'login':
      return {...state, ...action.data }
    case 'logout':
      return {...state, ...action.data }
    default:
      return {...state}
  }
}
export default function Home() {

  const [state,dispatch] = React.useReducer(appReducer,{
    loggedIn: false,  page: 'welcome', user: null,
  })
  const {page,loggedIn,user} = state

  React.useEffect(()=>{

    async function main(){

      const user = await fetchJson('/api/user/user')    

      if(user.loggedIn){
        console.log(' Relogin ')
        dispatch({
          type:'login',
          data: {
            user: user,
            loggedIn: true,
            page: user.type,
          }
        })
      } 

    }
    main();

    

  },[])

  var main;
  
  switch(page){
    case 'welcome':
      main = <div> Welcome to Food Delivery Service</div>
      break;
    case 'login':
      main = <Login dispatch={dispatch} />
      break;
    case 'register':
      main = <Register dispatch={dispatch} />
      break;
    case 'regular':
      main = <div>REGULAR USER </div>
      break;
    case 'restaurant':
      main = <Restaurant state={state} dispatch={dispatch} />
      break;
      // Eo switch
  }
  

  // main = <Login state={state} />
  
  return (
    <div className={home.page}>
      <Head>
        <title>NEXT food delivery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header state={state} dispatch={dispatch} />

      <main className={home.main} >{main}</main>

      <footer></footer>
    </div>
  )
}
